"""init

Revision ID: f12a761ae626
Revises: 
Create Date: 2026-06-24 19:57:27.895018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12a761ae626'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('documents_embedding_idx'), table_name='documents', postgresql_using='ivfflat')
    op.drop_index(op.f('documents_requested_by_idx'), table_name='documents')
    op.drop_column('documents', 'requested_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('requested_by', sa.TEXT(), server_default=sa.text("'anonymous'::text"), autoincrement=False, nullable=False))
    op.create_index(op.f('documents_requested_by_idx'), 'documents', ['requested_by'], unique=False)
    op.create_index(op.f('documents_embedding_idx'), 'documents', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.alter_column('documents', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
